name: test-haskell-header-loading
license: CC0-1.0
license-file: LICENSE

verbatim:
  cabal-version: 2.2

dependencies:
  - base >= 4.7 && < 5

pkg-config-dependencies:
  - openssl

executables:
  test-haskell-gtk:
    main: Main.hs
    source-dirs: src
    dependencies:
      - base >= 4.7 && < 5
